name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4


      - name: Run a one-line script
        run: echo Hello, world!


      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: build docker
        run: docker build -t ghrc.io/anton3078/320_os_github_actions/node-app:latest .
      -
       name: Push
       run: docker push ghrc.io/anton3078/320_os_github_actions/node-app:latest
